a=input("Enter Name :")

Tuple1=tuple(a)
for i in Tuple1:
    if i=="A" or i=="a":
        print(" * * * ")
        print("*     *")
        print("*     *")
        print("* * * *")
        print("*     *")
        print("*     *")

        print()
    elif i=="B" or i=="b":
        print(" * * * ")
        print("*     *")
        print("*     *")
        print("* * *")
        print("*     *")
        print("*     *")
        print(" * * * ")
        print()
    elif i=="C" or i=="c":
        print(" * * *")
        print("*")
        print("*")
        print("*")
        print(" * * *")
        print()
    elif i=="D" or i=="d":
        print("* * *")
        print("*     *")
        print("*     *")
        print("*     *")
        print("* * *")
        print()
    elif i=="E" or i=="e":
        print("* * * *")
        print("*    ")
        print("* * * *")
        print("*     ")
        print("* * * *")
        print()
    elif i=="F" or i=="f":
        print("* * * *")
        print("*    ")
        print("* * * *")
        print("*     ")
        print("* ")
        print()
    elif i=="G" or i=="g":
        print("* * * *")
        print("*    ")
        print("*   * *")
        print("*     *")
        print("* * * * ")
        print()
    elif i=="H" or i=="h":
        print("*     *")
        print("*     *")
        print("* * * *")
        print("*     *")
        print("*     * ")
        print()
    elif i=="I" or i=="i":
        print("* * * *")
        print("   *    ")
        print("   *   ")
        print("   *     ")
        print("* * * * ")
        print()
    elif i=="J" or i=="j":
        print("* * * *")
        print("    *    ")
        print("    *  ")
        print("*   *   ")
        print(" * *  ")
        print()
    elif i=="K" or i=="k":
        print("*     *")
        print("*   *")
        print("* *  ")
        print("*   * ")
        print("*     * ")
        print()
    elif i=="L" or i=="l":
        print("* ")
        print("*    ")
        print("*   ")
        print("*    ")
        print("* * * * ")
        print()
    elif i=="M" or i=="m":
        print("*     *")
        print("* * * *")
        print("*  *  *")
        print("*     *")
        print("*     * ")
        print()
    elif i=="N" or i=="n":
        print("*     *")
        print("* *   *")
        print("*  *  *")
        print("*   * *")
        print("*     * ")
        print()
    elif i=="O" or i=="o":
        print(" * * *")
        print("*     *")
        print("*     *")
        print("*     *")
        print(" * * *")
        print()
    elif i=="P" or i=="p":
        print("* * *")
        print("*     *")
        print("* * * ")
        print("*     ")
        print("* ")
        print()
    elif i=="Q" or i=="q":
        print(" * * *")
        print("*     *")
        print("*     *")
        print("*   * *")
        print(" * * *")
        print("       *")
        print()
    elif i=="R" or i=="r":
        print("* * *")
        print("*     *")
        print("* * * ")
        print("*   *   ")
        print("*     *")
        print()
    elif i=="S" or i=="s":
        print(" * * *")
        print("*     ")
        print(" * * * ")
        print("      *")
        print(" * * * ")
        print()
    elif i=="T" or i=="t":
        print("* * * *")
        print("   *    ")
        print("   *   ")
        print("   *     ")
        print("   *")
        print()
    elif i=="U" or i=="u":
        print("*     *")
        print("*     *")
        print("*     *")
        print("*     *")
        print(" * * *")
        print()
    elif i=="V" or i=="v":
        print("*     *")
        print(" *   *")
        print("  * *")
        print("   *")
        print()
    elif i=="W" or i=="w":
        print("*     *")
        print("*     *")
        print("*  *  *")
        print("* * * *")
        print("*     * ")
        print()
    elif i=="X" or i=="x":
        print("*     *")
        print(" *   *")
        print("  * * ")
        print("  * *")
        print(' *   *')
        print("*     *")
        print()
    elif i=="Y" or i=="y":
        print("*     *")
        print(" *   *")
        print("  * * ")
        print("   * ")
        print('  *   ')
        print(" *    ")
        print()
    elif i=="Z" or i=="z":
        print("* * * *")
        print("     *")
        print("    * ")
        print("   * ")
        print("  *   ")
        print(" *")
        print("* * * *")
        print()
    
